kind = "DojoContract"
class_hash = "0x3ee32958b958017c667501bb85bb2411e2dd5c1e11bc2230fb947a75b8ec07e"
original_class_hash = "0x3ee32958b958017c667501bb85bb2411e2dd5c1e11bc2230fb947a75b8ec07e"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/octoguns-mapmaker-14c58c7d.json"
reads = []
writes = []
init_calldata = []
tag = "octoguns-mapmaker"
systems = [
    "default_map",
    "create",
]
manifest_name = "octoguns-mapmaker-14c58c7d"
