[world]
kind = "WorldContract"
class_hash = "0x6f38d5d9507c5d9546290e1a27e309efe5a9af3770b6cc1627db4a1b90a7dce"
original_class_hash = "0x6f38d5d9507c5d9546290e1a27e309efe5a9af3770b6cc1627db4a1b90a7dce"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x204849b9183d23d62291d90c3bbf935c4bda78659fd91dcb6d42fc2e4f109de"
transaction_hash = "0x106f617526657439d720008e6a8a69fbbf96763a241112e101c609f231e4c0d"
block_number = 13
seed = "pistols64-1"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x658a65db7d96b120dee55194fdd12c66052bc1a7f58751a3a83a97545f2b737"
class_hash = "0x670b9c653ad6bb61afb1e9ea05ac2c3f831cbb92808a639d201f2ef6cc1b30b"
original_class_hash = "0x670b9c653ad6bb61afb1e9ea05ac2c3f831cbb92808a639d201f2ef6cc1b30b"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pistols64-actions-67633088.json"
reads = []
writes = [
    "pistols64-Challenge",
    "pistols64-Round",
]
init_calldata = []
tag = "pistols64-actions"
systems = ["move"]
manifest_name = "pistols64-actions-67633088"

[[contracts]]
kind = "DojoContract"
address = "0x98390681154ffe96f336720aa65e5310df2b66fe1ec3351bad9ec972085f25"
class_hash = "0x1530ac6ce914d14580428a398d5f615c54b149291793ee152f91f4d538ddc9f"
original_class_hash = "0x1530ac6ce914d14580428a398d5f615c54b149291793ee152f91f4d538ddc9f"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pistols64-rng-6a1b2e03.json"
reads = []
writes = []
init_calldata = []
tag = "pistols64-rng"
systems = []
manifest_name = "pistols64-rng-6a1b2e03"

[[models]]
kind = "DojoModel"
class_hash = "0x39380a0b122e24f3eb936b3501a2fd7938902ff7be0a01c160b872ee8a81e40"
original_class_hash = "0x39380a0b122e24f3eb936b3501a2fd7938902ff7be0a01c160b872ee8a81e40"
abi = "manifests/dev/deployment/abis/models/pistols64-Challenge-4a2b5cb4.json"
tag = "pistols64-Challenge"
qualified_path = "pistols64::models::challenge::challenge"
manifest_name = "pistols64-Challenge-4a2b5cb4"

[[models.members]]
name = "duel_id"
type = "u128"
key = true

[[models.members]]
name = "address_a"
type = "ContractAddress"
key = false

[[models.members]]
name = "address_b"
type = "ContractAddress"
key = false

[[models.members]]
name = "duelist_name_a"
type = "felt252"
key = false

[[models.members]]
name = "duelist_name_b"
type = "felt252"
key = false

[[models.members]]
name = "message"
type = "felt252"
key = false

[[models.members]]
name = "state"
type = "ChallengeState"
key = false

[[models.members]]
name = "winner"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6f1679e224b9a9b9e07f4bdbb86fd451e3ea2f2e05894c047bd7c01d4e25452"
original_class_hash = "0x6f1679e224b9a9b9e07f4bdbb86fd451e3ea2f2e05894c047bd7c01d4e25452"
abi = "manifests/dev/deployment/abis/models/pistols64-Round-41ec1aaa.json"
tag = "pistols64-Round"
qualified_path = "pistols64::models::round::round"
manifest_name = "pistols64-Round-41ec1aaa"

[[models.members]]
name = "duel_id"
type = "u128"
key = true

[[models.members]]
name = "round_number"
type = "u8"
key = true

[[models.members]]
name = "shot_a"
type = "Shot"
key = false

[[models.members]]
name = "shot_b"
type = "Shot"
key = false
