tag = "octoguns-actions"
writes = [
    "octoguns-CharacterPosition",
    "octoguns-CharacterModel",
    "octoguns-Map",
    "octoguns-Session",
    "octoguns-SessionMeta",
    "octoguns-Bullet",
    "octoguns-TurnData",

]
