
// Generated by dojo-bindgen on Wed, 16 Oct 2024 14:59:51 +0000. Do not modify this file manually.
// Import the necessary types from the recs SDK
// generate again with `sozo build --typescript` 
import { defineComponent, Type as RecsType, type World } from "@dojoengine/recs";

export type ContractComponents = Awaited<ReturnType<typeof defineContractComponents>>;



// Type definition for `dojo::model::layout::Layout` enum
export type Layout = { type: 'Fixed'; value: RecsType.NumberArray; } | { type: 'Struct'; value: RecsType.StringArray; } | { type: 'Tuple'; value: RecsType.StringArray; } | { type: 'Array'; value: RecsType.StringArray; } | { type: 'ByteArray'; } | { type: 'Enum'; value: RecsType.StringArray; };

export const LayoutDefinition = {
    type: RecsType.String,
    value: RecsType.String
};
        
// Type definition for `core::byte_array::ByteArray` struct
export interface ByteArray {
    data: String[];
    pending_word: BigInt;
    pending_word_len: Number;
    
}
export const ByteArrayDefinition = {
    data: RecsType.StringArray,
    pending_word: RecsType.BigInt,
    pending_word_len: RecsType.Number,
    
};

// Type definition for `dojo::model::layout::FieldLayout` struct
export interface FieldLayout {
    selector: BigInt;
    layout: Layout;
    
}
export const FieldLayoutDefinition = {
    selector: RecsType.BigInt,
    layout: LayoutDefinition,
    
};

// Type definition for `planetary::models::planet::Planet` struct
export interface Planet {
    name: BigInt;
    world_address: BigInt;
    is_available: Boolean;
    
}
export const PlanetDefinition = {
    name: RecsType.BigInt,
    world_address: RecsType.BigInt,
    is_available: RecsType.Boolean,
    
};


export function defineContractComponents(world: World) {
    return {

        // Model definition for `planetary::models::planet::Planet` model
        Planet: (() => {
            return defineComponent(
                world,
                {
                    name: RecsType.BigInt,
                    world_address: RecsType.BigInt,
                    is_available: RecsType.Boolean,
                },
                {
                    metadata: {
                        namespace: "planetary",
                        name: "Planet",
                        types: ["felt252", "ContractAddress", "bool"],
                        customTypes: [],
                    },
                }
            );
        })(),
    };
}
