[world]
name = "Planetary"
description = "Planetary: connecting worlds"
icon_uri = "https://raw.githubusercontent.com/underware-gg/pistols-64/main/images/planetary-icon.png"
cover_uri = "https://raw.githubusercontent.com/underware-gg/pistols-64/main/images/planetary-cover.jpg"
website = "https://github.com/underware-gg/pistols-64"

seed = "planetaryasdf"

[world.socials]
x = "https://x.com/underware_gg"
github = "https://github.com/underware-gg/pistols-64"
# discord = "https://discord.gg/FB2wR6uF"
# telegram = "https://t.me/dojoengine"

[namespace]
default = "planetary"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address = "0x0694182a014b39855a1b139961a3f39e7d4b43527b30d892a630d66a2abe3780"
private_key = "0x0430638cc3ef026ad7a74d9ad143bfc15bf303cea0be1c972ab1f280c90a531a"
#world_address = "0x27ff3447ba2c7e891a1d6b03490d9d7038806cc58b2d214dcd5d2eb26376369"

[writers]
"planetary" = ["planetary-actions"]