kind = "DojoModel"
class_hash = "0x1a1f3caf725b56b1d7ac1abab41a86b93c63d989d7cf7744bc2f80d45a93eda"
original_class_hash = "0x1a1f3caf725b56b1d7ac1abab41a86b93c63d989d7cf7744bc2f80d45a93eda"
abi = "manifests/dev/base/abis/models/planetary-Planet-1feffb25.json"
tag = "planetary-Planet"
qualified_path = "planetary::models::planet::planet"
manifest_name = "planetary-Planet-1feffb25"

[[members]]
name = "name"
type = "felt252"
key = true

[[members]]
name = "world_address"
type = "ContractAddress"
key = false

[[members]]
name = "is_available"
type = "bool"
key = false
