kind = "DojoModel"
class_hash = "0x6b8a16f873de8e8114620c78c2f81dd2e73d581589eac580bbdbe81b343aca3"
original_class_hash = "0x6b8a16f873de8e8114620c78c2f81dd2e73d581589eac580bbdbe81b343aca3"
abi = "manifests/dev/base/abis/models/pistols64_planetelo-Player-680e55f2.json"
tag = "pistols64_planetelo-Player"
qualified_path = "pistols64::planetelo::planetelo::player"
manifest_name = "pistols64_planetelo-Player-680e55f2"

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "felt252"
key = false
