kind = "DojoModel"
class_hash = "0x6f1679e224b9a9b9e07f4bdbb86fd451e3ea2f2e05894c047bd7c01d4e25452"
original_class_hash = "0x6f1679e224b9a9b9e07f4bdbb86fd451e3ea2f2e05894c047bd7c01d4e25452"
abi = "manifests/dev/base/abis/models/pistols64-Round-41ec1aaa.json"
tag = "pistols64-Round"
qualified_path = "pistols64::models::round::round"
manifest_name = "pistols64-Round-41ec1aaa"

[[members]]
name = "duel_id"
type = "u128"
key = true

[[members]]
name = "round_number"
type = "u8"
key = true

[[members]]
name = "shot_a"
type = "Shot"
key = false

[[members]]
name = "shot_b"
type = "Shot"
key = false
