kind = "DojoModel"
class_hash = "0xe7d289c00d1a4afcd4dad4e488623772215f5d61719f089eb32f6b752823d3"
original_class_hash = "0xe7d289c00d1a4afcd4dad4e488623772215f5d61719f089eb32f6b752823d3"
abi = "manifests/dev/base/abis/models/matchmaking-Elo-155b64e4.json"
tag = "matchmaking-Elo"
qualified_path = "matchmaking::models::elo::elo"
manifest_name = "matchmaking-Elo-155b64e4"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "game"
type = "felt252"
key = true

[[members]]
name = "value"
type = "u64"
key = false
