kind = "DojoContract"
class_hash = "0xc0d2fa0937cfbced755e5e242f62c6ff383c5fe23bfb489b6c1946a7afc911"
original_class_hash = "0xc0d2fa0937cfbced755e5e242f62c6ff383c5fe23bfb489b6c1946a7afc911"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/planetary-planetary_actions-3d857935.json"
reads = []
writes = []
init_calldata = []
tag = "planetary-planetary_actions"
systems = [
    "register",
    "unregister",
]
manifest_name = "planetary-planetary_actions-3d857935"
