kind = "DojoContract"
class_hash = "0x3a87a3dc1ab63e9485cbc7938a4775e76a4f63e5e6a45cce94fba4908ef6e3e"
original_class_hash = "0x3a87a3dc1ab63e9485cbc7938a4775e76a4f63e5e6a45cce94fba4908ef6e3e"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols64-planetelo-56d73f5a.json"
reads = []
writes = []
init_calldata = []
tag = "pistols64-planetelo"
systems = ["register_player"]
manifest_name = "pistols64-planetelo-56d73f5a"
