kind = "DojoContract"
class_hash = "0x670b9c653ad6bb61afb1e9ea05ac2c3f831cbb92808a639d201f2ef6cc1b30b"
original_class_hash = "0x670b9c653ad6bb61afb1e9ea05ac2c3f831cbb92808a639d201f2ef6cc1b30b"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols64-actions-67633088.json"
reads = []
writes = []
init_calldata = []
tag = "pistols64-actions"
systems = ["move"]
manifest_name = "pistols64-actions-67633088"
