kind = "DojoContract"
class_hash = "0x1319a3cda6d7ff385840e1a15ca45449d3ccdfde216e52bec42246d67919679"
original_class_hash = "0x1319a3cda6d7ff385840e1a15ca45449d3ccdfde216e52bec42246d67919679"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols64-rng-6a1b2e03.json"
reads = []
writes = []
init_calldata = []
tag = "pistols64-rng"
systems = []
manifest_name = "pistols64-rng-6a1b2e03"
