kind = "DojoContract"
class_hash = "0x3cde4604fc69a14f047c3297f996b43afce6d9d9e420f9899c9c31a4a75525f"
original_class_hash = "0x3cde4604fc69a14f047c3297f996b43afce6d9d9e420f9899c9c31a4a75525f"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/matchmaking-actions-7c1ce329.json"
reads = []
writes = []
init_calldata = []
tag = "matchmaking-actions"
systems = []
manifest_name = "matchmaking-actions-7c1ce329"
