[world]
kind = "WorldContract"
class_hash = "0x5c4271c8cd454ceb8049d2b0724c99d12c2ef8077fc6ad325b18978f614aab0"
original_class_hash = "0x5c4271c8cd454ceb8049d2b0724c99d12c2ef8077fc6ad325b18978f614aab0"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x7447477a7c852c946f0b8d13ebdfe0db9e78f3de60ab799320691502b4d32a3"
transaction_hash = "0x2c9a77cb6bb6e0cc6b86b67481b0e685c33a10f942457cf03333c9defe47223"
block_number = 3
seed = "octoguns"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x11de1871e7fa8ac97e62c36724c32ee584982f4a5892b4f62fd545d7ab2d506"
class_hash = "0x5f41b8b6740575e35a7da94e08c6af4fbd365e8025ababee1dd0acac8045031"
original_class_hash = "0x5f41b8b6740575e35a7da94e08c6af4fbd365e8025ababee1dd0acac8045031"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/octoguns-actions-3f08332a.json"
reads = []
writes = [
    "octoguns-CharacterPosition",
    "octoguns-CharacterModel",
    "octoguns-Map",
    "octoguns-Session",
    "octoguns-SessionMeta",
    "octoguns-Bullet",
    "octoguns-TurnData",
]
init_calldata = []
tag = "octoguns-actions"
systems = ["move"]
manifest_name = "octoguns-actions-3f08332a"

[[contracts]]
kind = "DojoContract"
address = "0x11e7a657668ca83c556f7545ab5bde00c1a1275c6c9ed17bea33104fcda2f3b"
class_hash = "0x3ee32958b958017c667501bb85bb2411e2dd5c1e11bc2230fb947a75b8ec07e"
original_class_hash = "0x3ee32958b958017c667501bb85bb2411e2dd5c1e11bc2230fb947a75b8ec07e"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/octoguns-mapmaker-14c58c7d.json"
reads = []
writes = [
    "octoguns-CharacterPosition",
    "octoguns-CharacterModel",
    "octoguns-Map",
    "octoguns-Session",
    "octoguns-SessionMeta",
    "octoguns-Bullet",
    "octoguns-Global",
]
init_calldata = []
tag = "octoguns-mapmaker"
systems = [
    "default_map",
    "create",
]
manifest_name = "octoguns-mapmaker-14c58c7d"

[[contracts]]
kind = "DojoContract"
address = "0x57a72dd6f0bf3b0ced0fd50e54696643b8e3b38e226a150a1471c658355921e"
class_hash = "0x29601d131c2a760259e8a670150e74fd5c7c88dd0613b894d1670fdf741486e"
original_class_hash = "0x29601d131c2a760259e8a670150e74fd5c7c88dd0613b894d1670fdf741486e"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/octoguns-spawn-1acb0980.json"
reads = []
writes = [
    "octoguns-CharacterPosition",
    "octoguns-CharacterModel",
    "octoguns-Map",
    "octoguns-Session",
    "octoguns-SessionMeta",
    "octoguns-Bullet",
    "octoguns-Player",
]
init_calldata = []
tag = "octoguns-spawn"
systems = ["spawn"]
manifest_name = "octoguns-spawn-1acb0980"

[[contracts]]
kind = "DojoContract"
address = "0x44ce069fe53c5c7941eec521bc9e876907d5da6ca273a98b78f1cbbcfea5b62"
class_hash = "0x623bd6af3f6a90aa5a1bb9d7f7a18819afbee64365cc8ba95f683f5b45bbefe"
original_class_hash = "0x623bd6af3f6a90aa5a1bb9d7f7a18819afbee64365cc8ba95f683f5b45bbefe"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/octoguns-start-5506b80f.json"
reads = []
writes = [
    "octoguns-CharacterPosition",
    "octoguns-CharacterModel",
    "octoguns-Map",
    "octoguns-Session",
    "octoguns-SessionMeta",
    "octoguns-Bullet",
    "octoguns-Global",
    "octoguns-Player",
    "octoguns-SessionPrimitives",
]
init_calldata = []
tag = "octoguns-start"
systems = [
    "create_closed",
    "join",
]
manifest_name = "octoguns-start-5506b80f"

[[models]]
kind = "DojoModel"
class_hash = "0x5e0d858c19586c631802aa462ab7cb204912efe0d8f468305054d0db1344cb7"
original_class_hash = "0x5e0d858c19586c631802aa462ab7cb204912efe0d8f468305054d0db1344cb7"
abi = "manifests/dev/deployment/abis/models/octoguns-Bullet-69e7a9ab.json"
tag = "octoguns-Bullet"
qualified_path = "octoguns::models::bullet::bullet"
manifest_name = "octoguns-Bullet-69e7a9ab"

[[models.members]]
name = "bullet_id"
type = "u32"
key = true

[[models.members]]
name = "shot_step"
type = "u16"
key = false

[[models.members]]
name = "shot_by"
type = "u32"
key = false

[[models.members]]
name = "shot_at"
type = "Vec2"
key = false

[[models.members]]
name = "velocity"
type = "IVec2"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x660f2f126db3f73a49645f5a1db074be8c3dafc090bc0afe81cefa4d10b7f3d"
original_class_hash = "0x660f2f126db3f73a49645f5a1db074be8c3dafc090bc0afe81cefa4d10b7f3d"
abi = "manifests/dev/deployment/abis/models/octoguns-CharacterModel-66c7439d.json"
tag = "octoguns-CharacterModel"
qualified_path = "octoguns::models::characters::character_model"
manifest_name = "octoguns-CharacterModel-66c7439d"

[[models.members]]
name = "entity_id"
type = "u32"
key = true

[[models.members]]
name = "session_id"
type = "u32"
key = false

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = false

[[models.members]]
name = "steps_amount"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x67e24ab3c6231d59ebfa89355dc6723dd98f47baf73c048e9f64791c9e26e59"
original_class_hash = "0x67e24ab3c6231d59ebfa89355dc6723dd98f47baf73c048e9f64791c9e26e59"
abi = "manifests/dev/deployment/abis/models/octoguns-CharacterPosition-66fdf8ab.json"
tag = "octoguns-CharacterPosition"
qualified_path = "octoguns::models::characters::character_position"
manifest_name = "octoguns-CharacterPosition-66fdf8ab"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "coords"
type = "Vec2"
key = false

[[models.members]]
name = "max_steps"
type = "u32"
key = false

[[models.members]]
name = "current_step"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x26c0fcbfc402b24c8481866784bc2edbbaa7321ec12cb435fca258f76fea25"
original_class_hash = "0x26c0fcbfc402b24c8481866784bc2edbbaa7321ec12cb435fca258f76fea25"
abi = "manifests/dev/deployment/abis/models/octoguns-Global-23c9ff90.json"
tag = "octoguns-Global"
qualified_path = "octoguns::models::global::global"
manifest_name = "octoguns-Global-23c9ff90"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "pending_sessions"
type = "Array<u32>"
key = false

[[models.members]]
name = "map_count"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x771761ae192b1dc49b25667346a4c42739ed0e87e48e92afd548f9592ab9d6f"
original_class_hash = "0x771761ae192b1dc49b25667346a4c42739ed0e87e48e92afd548f9592ab9d6f"
abi = "manifests/dev/deployment/abis/models/octoguns-Map-6508b277.json"
tag = "octoguns-Map"
qualified_path = "octoguns::models::map::map"
manifest_name = "octoguns-Map-6508b277"

[[models.members]]
name = "map_id"
type = "u32"
key = true

[[models.members]]
name = "map_objects"
type = "Array<u16>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x40b4e50b38be60baa3ab53f71331d733346d71048f0835abebe0219ee00313"
original_class_hash = "0x40b4e50b38be60baa3ab53f71331d733346d71048f0835abebe0219ee00313"
abi = "manifests/dev/deployment/abis/models/octoguns-Player-5a4c6c7b.json"
tag = "octoguns-Player"
qualified_path = "octoguns::models::player::player"
manifest_name = "octoguns-Player-5a4c6c7b"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "games"
type = "Array<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3fc1d9de1c4b38b0e29db41d9c3b9bc32276aafc0088c21f4d92b4bd9f3e49d"
original_class_hash = "0x3fc1d9de1c4b38b0e29db41d9c3b9bc32276aafc0088c21f4d92b4bd9f3e49d"
abi = "manifests/dev/deployment/abis/models/octoguns-Session-41d1f2ce.json"
tag = "octoguns-Session"
qualified_path = "octoguns::models::sessions::session"
manifest_name = "octoguns-Session-41d1f2ce"

[[models.members]]
name = "session_id"
type = "u32"
key = true

[[models.members]]
name = "player1"
type = "ContractAddress"
key = false

[[models.members]]
name = "player2"
type = "ContractAddress"
key = false

[[models.members]]
name = "map_id"
type = "u32"
key = false

[[models.members]]
name = "state"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x28f28d0f03544299f5be80803fd6c00c5226857cfb2580d4f5de12ccc4aab82"
original_class_hash = "0x28f28d0f03544299f5be80803fd6c00c5226857cfb2580d4f5de12ccc4aab82"
abi = "manifests/dev/deployment/abis/models/octoguns-SessionMeta-4f7fd982.json"
tag = "octoguns-SessionMeta"
qualified_path = "octoguns::models::sessions::session_meta"
manifest_name = "octoguns-SessionMeta-4f7fd982"

[[models.members]]
name = "session_id"
type = "u32"
key = true

[[models.members]]
name = "turn_count"
type = "u32"
key = false

[[models.members]]
name = "p1_character"
type = "u32"
key = false

[[models.members]]
name = "p2_character"
type = "u32"
key = false

[[models.members]]
name = "bullets"
type = "Array<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x557c8f93ab95b683d7a467f9838893a63a782bd65a4d747a96ad2630c9789cd"
original_class_hash = "0x557c8f93ab95b683d7a467f9838893a63a782bd65a4d747a96ad2630c9789cd"
abi = "manifests/dev/deployment/abis/models/octoguns-SessionPrimitives-29e33ecc.json"
tag = "octoguns-SessionPrimitives"
qualified_path = "octoguns::models::sessions::session_primitives"
manifest_name = "octoguns-SessionPrimitives-29e33ecc"

[[models.members]]
name = "session_id"
type = "u32"
key = true

[[models.members]]
name = "bullet_speed"
type = "u64"
key = false

[[models.members]]
name = "bullet_sub_steps"
type = "u32"
key = false

[[models.members]]
name = "bullets_per_turn"
type = "u32"
key = false

[[models.members]]
name = "sub_moves_per_turn"
type = "u32"
key = false

[[models.members]]
name = "max_distance_per_sub_move"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x28ec07b8933b445f9dcc40ec316b0636b59c869fd2dc62de8d58166e83fb057"
original_class_hash = "0x28ec07b8933b445f9dcc40ec316b0636b59c869fd2dc62de8d58166e83fb057"
abi = "manifests/dev/deployment/abis/models/octoguns-TurnData-293d224e.json"
tag = "octoguns-TurnData"
qualified_path = "octoguns::models::turndata::turn_data"
manifest_name = "octoguns-TurnData-293d224e"

[[models.members]]
name = "session_id"
type = "u32"
key = true

[[models.members]]
name = "turn_number"
type = "u32"
key = true

[[models.members]]
name = "moves"
type = "TurnMove"
key = false
