kind = "DojoModel"
class_hash = "0x26c0fcbfc402b24c8481866784bc2edbbaa7321ec12cb435fca258f76fea25"
original_class_hash = "0x26c0fcbfc402b24c8481866784bc2edbbaa7321ec12cb435fca258f76fea25"
abi = "manifests/dev/base/abis/models/octoguns-Global-23c9ff90.json"
tag = "octoguns-Global"
qualified_path = "octoguns::models::global::global"
manifest_name = "octoguns-Global-23c9ff90"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "pending_sessions"
type = "Array<u32>"
key = false

[[members]]
name = "map_count"
type = "u32"
key = false
