kind = "DojoModel"
class_hash = "0x28ec07b8933b445f9dcc40ec316b0636b59c869fd2dc62de8d58166e83fb057"
original_class_hash = "0x28ec07b8933b445f9dcc40ec316b0636b59c869fd2dc62de8d58166e83fb057"
abi = "manifests/dev/base/abis/models/octoguns-TurnData-293d224e.json"
tag = "octoguns-TurnData"
qualified_path = "octoguns::models::turndata::turn_data"
manifest_name = "octoguns-TurnData-293d224e"

[[members]]
name = "session_id"
type = "u32"
key = true

[[members]]
name = "turn_number"
type = "u32"
key = true

[[members]]
name = "moves"
type = "TurnMove"
key = false
