kind = "DojoModel"
class_hash = "0x3fc1d9de1c4b38b0e29db41d9c3b9bc32276aafc0088c21f4d92b4bd9f3e49d"
original_class_hash = "0x3fc1d9de1c4b38b0e29db41d9c3b9bc32276aafc0088c21f4d92b4bd9f3e49d"
abi = "manifests/dev/base/abis/models/octoguns-Session-41d1f2ce.json"
tag = "octoguns-Session"
qualified_path = "octoguns::models::sessions::session"
manifest_name = "octoguns-Session-41d1f2ce"

[[members]]
name = "session_id"
type = "u32"
key = true

[[members]]
name = "player1"
type = "ContractAddress"
key = false

[[members]]
name = "player2"
type = "ContractAddress"
key = false

[[members]]
name = "map_id"
type = "u32"
key = false

[[members]]
name = "state"
type = "u8"
key = false
