kind = "DojoModel"
class_hash = "0x28f28d0f03544299f5be80803fd6c00c5226857cfb2580d4f5de12ccc4aab82"
original_class_hash = "0x28f28d0f03544299f5be80803fd6c00c5226857cfb2580d4f5de12ccc4aab82"
abi = "manifests/dev/base/abis/models/octoguns-SessionMeta-4f7fd982.json"
tag = "octoguns-SessionMeta"
qualified_path = "octoguns::models::sessions::session_meta"
manifest_name = "octoguns-SessionMeta-4f7fd982"

[[members]]
name = "session_id"
type = "u32"
key = true

[[members]]
name = "turn_count"
type = "u32"
key = false

[[members]]
name = "p1_character"
type = "u32"
key = false

[[members]]
name = "p2_character"
type = "u32"
key = false

[[members]]
name = "bullets"
type = "Array<u32>"
key = false
