kind = "DojoModel"
class_hash = "0x40b4e50b38be60baa3ab53f71331d733346d71048f0835abebe0219ee00313"
original_class_hash = "0x40b4e50b38be60baa3ab53f71331d733346d71048f0835abebe0219ee00313"
abi = "manifests/dev/base/abis/models/octoguns-Player-5a4c6c7b.json"
tag = "octoguns-Player"
qualified_path = "octoguns::models::player::player"
manifest_name = "octoguns-Player-5a4c6c7b"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "games"
type = "Array<u32>"
key = false
