kind = "DojoModel"
class_hash = "0x5e0d858c19586c631802aa462ab7cb204912efe0d8f468305054d0db1344cb7"
original_class_hash = "0x5e0d858c19586c631802aa462ab7cb204912efe0d8f468305054d0db1344cb7"
abi = "manifests/dev/base/abis/models/octoguns-Bullet-69e7a9ab.json"
tag = "octoguns-Bullet"
qualified_path = "octoguns::models::bullet::bullet"
manifest_name = "octoguns-Bullet-69e7a9ab"

[[members]]
name = "bullet_id"
type = "u32"
key = true

[[members]]
name = "shot_step"
type = "u16"
key = false

[[members]]
name = "shot_by"
type = "u32"
key = false

[[members]]
name = "shot_at"
type = "Vec2"
key = false

[[members]]
name = "velocity"
type = "IVec2"
key = false
